// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlc

import (
	"context"
	"time"
)

const insertRunLog = `-- name: InsertRunLog :exec
INSERT INTO agg_meta (created_at)
VALUES ($1)
`

func (q *Queries) InsertRunLog(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, insertRunLog, createdAt)
	return err
}

const lastRun = `-- name: LastRun :one
SELECT created_at
FROM agg_meta
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LastRun(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, lastRun)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}
