// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type AggMetum struct {
	CreatedAt time.Time
}

type AggRepo struct {
	Owner            string
	Name             string
	Description      sql.NullString
	Language         sql.NullString
	Homepage         sql.NullString
	ForksCount       sql.NullInt32
	NetworkCount     sql.NullInt32
	OpenIssuesCount  sql.NullInt32
	StargazersCount  sql.NullInt32
	SubscribersCount sql.NullInt32
	WatchersCount    sql.NullInt32
	Size             sql.NullInt32
	Fork             sql.NullBool
	DefaultBranch    sql.NullString
	MasterBranch     sql.NullString
	CreatedAt        sql.NullTime
	PushedAt         sql.NullTime
	UpdatedAt        sql.NullTime
	RefreshedAt      sql.NullTime
}

type AggUser struct {
	Login       string
	Email       sql.NullString
	Location    sql.NullString
	Hireable    sql.NullBool
	Blog        sql.NullString
	Bio         sql.NullString
	Followers   sql.NullInt32
	Following   sql.NullInt32
	PublicRepos sql.NullInt32
	PublicGists sql.NullInt32
	AvatarUrl   sql.NullString
	DiskUsage   sql.NullInt32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Type        sql.NullString
	Name        sql.NullString
	Hide        bool
	IsAdmin     bool
	RefreshedAt sql.NullTime
	Company     string
}

type Migration struct {
	Name string
}
